### ISSUE TITLE
Cannot use manager app

### ISSUE THREAD

**Issue by jar349** [docker-library/tomcat#15]
Your documentation mentions that you don't have any users defined in `$CATALINA_HOME/conf/tomcat-users.xml`.  That's fine for obvious security reasons.

I'm using vagrant to provision a centos box with docker and I want to run your tomcat image in a docker container and be able to access the manager app.  How do you recommend that I edit the container's `$CATALINA_HOME/conf/tomcat-users.xml` file to define a user -- in an automated way?

I very stupidly tried to use `docker run --name=tomcat-container -d -p 8080:8080 -v /vagrant/.tomcat:/usr/local/tomcat tomcat:8-jre8` which blew away the entire /usr/local/tomcat directory (this is correct docker behavior - I'm just dumb).

What I was able to finally do was change the volume mapping like so: `docker run -d -p 8080:8080 -v /vagrant/.tomcat:/var/tomcat-config tomcat:8-jre8` and then write a `tomcat-users.xml` file out to `/vagrant/.tomcat` and then `docker exec tomcat-container cp /var/tomcat-config/tomcat-users.xml /usr/local/tomcat/conf` followed by `docker stop tomcat-container` and `docker start tomcat-container`.  But this is quite an ugly hack, wouldn't you agree?

Is there a better way to accomplish this?

**Comment by bryantrobbins** [comment]
If possible, you could create your own image, using this as a base. When defining your own image, you can stage your own files, assuming they don't need to change. I happened to be putting together a tiny example of this, if it's helpful:

https://github.com/bryantrobbins/docker-tomcat-example

(If files do need to change every time the container is run, you could build this dynamic capability into a "starter script". There are some examples of this around, like this Dockerfile and script from the mongo container: https://github.com/docker-library/mongo/tree/master/3.1 . )

**Comment by md5** [comment]
@jar349 You should be able to mount just that file with something like `-v /path/to/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro`

**Comment by larsvanmourik** [comment]
I extended the base image and added my own tomcat-users.xml to this end, and it works fine for the tomcat 8.0 base image:
`FROM tomcat:8.0-jre8`
`ADD tomcat-users.xml $CATALINA_HOME/conf`
But when I extend from the tomcat 8.5 base image I get a `403 Access Denied`. Did this functionality change going from 8.0 to 8.5 ? I can't seem to find it in the migration docs.

**Comment by Moghedrin** [comment]
The original issue seems to have been resolved, and a change in functionality in tomcat is outside the scope of the docker image itself. I'm closing this issue for now: if it comes back up, we can reopen.

**Comment by larsvanmourik** [comment]
The problem is that Tomcat doesn't list any change in functionality on that part that I can find and before I report a bug about it I would like to have some confirmation from other users that it is indeed a bug and not some oversight on my side. It's a pretty simple test to do so I thought I'd ask here, where people are (were) already looking into a similar issue.

**Comment by donovanmuller** [comment]
@larsvanmourik Just experienced the same issue (`403 Access Denied`) with `tomcat:8.5-alpine`. The bug you mention was fixed in 8.5.1 but the 403 issue still appears with 8.5.4.

With `tomcat:8.0-alpine` it works...

**Comment by NicoTexas** [comment]
Same here 403 error when trying to access to the manager. The bug is on Tomcat as I tried on a locally installed Tomcat 8.5.4 and same issue.

**Comment by An0nymous0** [comment]
@NicoTexas Thank you, Can be solved

**Comment by benweizhu** [comment]
https://stackoverflow.com/questions/36703856/access-tomcat-manager-app-from-different-host

**Comment by KINGSABRI** [comment]
What works for me in very simple steps 

**terminal 1**
```
docker run -it -p 8888:8080 -v /absulte/path/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml tomcat:8.0
```

**terminal 2**
```
docker exec -i -t [CONTAINER_NAME] /bin/bash
cat conf/tomcat-users.xml   # check if your file is loaded
```

**terminal 3**
```
docker stop [CONTAINER_NAME]
docker start [CONTAINER_NAME]
```

**tomcat-users.xml**
```xml
<tomcat-users>

  <role rolename="manager"/>
  <user username="admin" password="admin" roles="manager"/>
  <role rolename="admin-gui"/>
  <user username="admin" password="admin" roles="admin-gui"/>

</tomcat-users>
```

**Comment by EHJ-52n** [comment]
> tomcat-users.xml
> ```
> <tomcat-users>
> 
>   <role rolename="admin-gui"/>
>   <user username="tomcat" password="s3cret" roles="manager-gui"/>
> 
> </tomcat-users>
> ```

Is there a problem with the difference between `admin-gui` in `rolename` and `manager-gui` in `roles`?
